/*
 * (C) Copyright 2021-2023 UCAR
 * (C) Copyright 2023 Meteorologisk Institutt
 * (C) Crown Copyright 2024 Met Office
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 */

#pragma once

#include <math.h>
#include <omp.h>

#include <algorithm>
#include <limits>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

#include "atlas/functionspace.h"
#include "atlas/util/Earth.h"

#include "eckit/config/Configuration.h"
#include "eckit/exception/Exceptions.h"
#include "eckit/mpi/Comm.h"

#include "oops/interface/Geometry.h"
#include "oops/interface/Increment.h"
#include "oops/base/Increment4D.h"
#include "saber/oops/instantiateCovarFactory.h"
#include "oops/base/ModelSpaceCovariance4DBase.h"
#include "oops/base/PostProcessor.h"
#include "oops/interface/State.h"
#include "oops/base/State4D.h"
#include "oops/interface/Model.h"
#include "oops/interface/Variables.h"
#include "oops/runs/Application.h"
#include "oops/util/ConfigFunctions.h"
#include "oops/util/ConfigHelpers.h"
#include "oops/util/DateTime.h"
#include "oops/util/FieldSetHelpers.h"
#include "oops/util/Logger.h"
#include "oops/util/parameters/OptionalParameter.h"
#include "oops/util/parameters/Parameter.h"
#include "oops/util/parameters/Parameters.h"
#include "oops/util/parameters/RequiredParameter.h"

#include "saber/blocks/SaberParametricBlockChain.h"
#include "saber/oops/ErrorCovarianceParameters.h"
#include "oops/util/ECUtilities.h"
#include "saber/oops/Utilities.h"
#include "saber/util/HorizontalProfiles.h"

namespace saber {

// -----------------------------------------------------------------------------

/// \brief Top-level options taken by the ErrorCovarianceToolbox application.
class ErrorCovarianceToolboxParameters :
  public oops::Parameters {
  OOPS_CONCRETE_PARAMETERS(ErrorCovarianceToolboxParameters, oops::Parameters)

 public:
  /// Geometry parameters.
  oops::RequiredParameter<eckit::LocalConfiguration> geometry{"geometry", this};

  /// Background parameters.
  oops::RequiredParameter<eckit::LocalConfiguration> background{"background", this};

  /// Background error covariance model.
  oops::RequiredParameter<ErrorCovarianceParameters> backgroundError{"background error", this};

  /// Geometry parameters.
  oops::Parameter<bool> parallel{"parallel subwindows", true, this};

  /// Outer variables parameters
  oops::OptionalParameter<oops::JediVariables> incrementVars{"increment variables", this};

  /// Dirac location/variables parameters.
  oops::OptionalParameter<eckit::LocalConfiguration> dirac{"dirac", this};

  /// Diagnostic location/variables parameters.
  oops::OptionalParameter<eckit::LocalConfiguration> diagnostic{"diagnostic points", this};

  /// Where to write the output(s) of Dirac tests
  oops::OptionalParameter<eckit::LocalConfiguration> outputDirac{"output dirac", this};

  /// Whether and where to write the perturbations generated by the randomization.
  oops::OptionalParameter<eckit::LocalConfiguration> outputPerturbations{"output perturbations",
    this};

  /// Whether and where to write the states generated by the randomization.
  oops::OptionalParameter<eckit::LocalConfiguration> outputStates{"output states", this};

  /// Where to write the output of randomized variance.
  oops::OptionalParameter<eckit::LocalConfiguration> outputVariance{"output variance", this};

  /// Whether and how to compute unidimensional covariance profiles for isotropic cases
  oops::OptionalParameter<eckit::LocalConfiguration> covarianceProfile{
                                    "covariance profile", this};
};

// -----------------------------------------------------------------------------

template <typename MODEL> class ErrorCovarianceToolbox : public oops::Application {
  typedef oops::ModelSpaceCovariance4DBase<MODEL>         Covariance4DBase_;
  typedef oops::Covariance4DFactory<MODEL>                Covariance4DFactory_;
  typedef oops::Geometry<MODEL>                           Geometry_;
  typedef oops::Increment<MODEL>                          Increment_;
  typedef oops::Increment4D<MODEL>                        Increment4D_;
  typedef oops::Model<MODEL>                              Model_;
  typedef oops::State<MODEL>                              State_;
  typedef oops::State4D<MODEL>                            State4D_;
  typedef oops::Localization<MODEL>                       Localization_;
  typedef oops::Variables<MODEL>                          Variables_;

 public:
// -----------------------------------------------------------------------------
  ErrorCovarianceToolbox() {
    instantiateCovarFactory<MODEL>();
  }

// -----------------------------------------------------------------------------

  virtual ~ErrorCovarianceToolbox() {}

// -----------------------------------------------------------------------------

  int execute(const eckit::Configuration & fullConfig) const {
    // Deserialize parameters
    ErrorCovarianceToolboxParameters params;
    params.deserialize(fullConfig);

    // Define space and time communicators
    const eckit::mpi::Comm * commSpace = &eckit::mpi::comm();

    // Get number of MPI tasks and OpenMP threads
    size_t ntasks = commSpace->size();
    size_t nthreads = 1;
#ifdef _OPENMP
    # pragma omp parallel
    {
      nthreads = omp_get_num_threads();
    }
#endif

    // Replace patterns in full configuration and deserialize parameters
    eckit::LocalConfiguration fullConfigUpdated(fullConfig);
    setMPI(fullConfigUpdated, ntasks, nthreads);
    params.deserialize(fullConfigUpdated);

    // Set precision for test channel
    oops::Log::test() << std::scientific
                      << std::setprecision(std::numeric_limits<double>::digits10+1);

    // Setup geometry
    const Geometry_ geom(params.geometry);

    // Setup model
    eckit::LocalConfiguration modelConf;
    if (fullConfigUpdated.has("model")) {
      modelConf = fullConfigUpdated.getSubConfiguration("model");
    }
    const Model_ model(geom, modelConf);

    // Setup background
    const State4D_ xx(params.background, geom, model);

    // Setup variables
    oops::JediVariables tmpVars(xx[0].state().fieldSet().field_names());
    if (params.incrementVars.value() != boost::none) {
      tmpVars = params.incrementVars.value().value();
    }
    for (auto & var : tmpVars) {
      var.setLevels(xx[0].state().fieldSet()[var.name()].shape(1));
    }
    const oops::JediVariables vars = tmpVars;

    // Covariance parameters
    const eckit::LocalConfiguration covarConf = params.backgroundError.value().toConfiguration();

    // Dirac test
    const auto & diracParams = params.dirac.value();
    if (diracParams != boost::none) {
      // Setup Dirac field
      Increment4D_ dxi(geom, util::templatedVars<MODEL>(vars), xx.times());
      dirac4D(*diracParams, dxi);
      oops::Log::test() << "Input Dirac increment:" << dxi << std::endl;

      // Test configuration
      eckit::LocalConfiguration testConf;

      // Add dirac configuration
      testConf.set("dirac", *diracParams);

      // Add diagnostic print configuration
      const auto & diagnostic = params.diagnostic.value();
      if (diagnostic != boost::none) {
        testConf.set("diagnostic points", *diagnostic);
      }

      // Add output Dirac configuration
      eckit::LocalConfiguration outputDiracUpdated = params.outputDirac.value().value();
      setMPI(outputDiracUpdated, ntasks, nthreads);
      testConf.set("output dirac", outputDiracUpdated);

      // Add covariance profile configuration
      const auto & profileConfig = params.covarianceProfile.value();
      if (profileConfig != boost::none) {
        testConf.set("covariance profile", *profileConfig);
      }

      // Apply B matrix components recursively
      const std::string id = "";
      dirac(covarConf, testConf, id, geom, vars, xx, dxi);
    }

    // Randomization
    const size_t & randomizationSize = params.backgroundError.value().randomizationSize.value();
    if (randomizationSize > 0) {
      randomization(params, geom, vars, covarConf, xx, ntasks, nthreads);
    }

    // If background error covariance has not been setup yet, do it now
    if (!diracParams && (randomizationSize == 0)) {
      std::unique_ptr<Covariance4DBase_> Bmat(Covariance4DFactory_::create(
                                              covarConf, geom, util::templatedVars<MODEL>(vars), xx));

      // Linearize
      Bmat->linearize(xx, geom, covarConf);
    }

    return 0;
  }

// -----------------------------------------------------------------------------

 private:
  std::string appname() const override {
    return "oops::ErrorCovarianceToolbox<" + MODEL::name() + ">";
  }

// -----------------------------------------------------------------------------

  void print_value_at_positions(const eckit::LocalConfiguration & diagConf,
                                const Geometry_ & geom,
                                const Increment4D_ & data) const {
    oops::Log::trace() << appname() << "::print_value_at_position starting" << std::endl;

    // Create diagnostic field
    Increment4D_ diagPoints(data);
    dirac4D(diagConf, diagPoints);

    // Get diagnostic values
    for (size_t jj = 0; jj < data.times().size(); ++jj) {
      util::printDiagValues(oops::mpi::myself(),
                            geom.geometry().getComm(),
                            geom.geometry().functionSpace(),
                            data[jj].increment().fieldSet(),
                            diagPoints[jj].increment().fieldSet());
    }

    oops::Log::trace() << appname() << "::print_value_at_position done" << std::endl;
  }

// -----------------------------------------------------------------------------

  void extract_1d_covariances(const eckit::LocalConfiguration & diracConf,
                              const eckit::LocalConfiguration & profileConf,
                              const Geometry_ & geom,
                              const Increment4D_ & data) const {
    oops::Log::trace() << appname() << "::extract_1d_covariances starting" << std::endl;

    if (data.times().size() > 1) {
      throw eckit::NotImplemented("Not implemented for 4D covariances", Here());
    }

    // Create dirac field
    Increment4D_ diracPoints(data);
    dirac4D(diracConf, diracPoints);

    // Define maximum length of horizontal profile
    double maxLength = std::numeric_limits<double>::infinity();
    if (profileConf.has("maximum distance")) {
      oops::Log::info() << "Info     : Reading user-provided maximum distance:" << std::endl;
      maxLength = profileConf.getDouble("maximum distance");
    } else {
      // If no maximum length input is given, try to compute a default value from the grid
      const auto & fspace = geom.geometry().functionSpace();
      if (fspace.type() == "StructuredColumns") {
        const atlas::functionspace::StructuredColumns fs(fspace);
        if (fs.grid().name().compare(0, 1, "F") == 0) {
          oops::Log::info() << "Info     : maximum distance computed as twice the cell "
                               "length at the Equator:" << std::endl;
          const int n = std::stoi(fs.grid().name().substr(1, std::string::npos));
          maxLength = atlas::util::Earth().radius() * M_PI / n;
        }
      } else if (fspace.type() == "NodeColumns") {
        const atlas::functionspace::NodeColumns fs(fspace);
        if (fs.mesh().grid().name().compare(0, 7, "CS-LFR-") == 0) {
          oops::Log::info() << "Info     : maximum distance computed as twice the cell "
                               "length at the Equator:" << std::endl;
          const int n = std::stoi(fs.mesh().grid().name().substr(7, std::string::npos));
          maxLength = atlas::util::Earth().radius() * M_PI / n;
        }
      }
    }
    oops::Log::info() << "Info     : maximum distance is " << maxLength << " m." << std::endl;

    // Boolean flag to remove duplicate points (is isotropy for instance)
    const bool removeDuplicates = profileConf.getBool("remove duplicate distances",
                                                      false);

    // Get values as a function of separation distance
    auto[distances, covariances, lons, lats, levs, fieldIndexes] =
        util::sortBySeparationDistance(geom.geometry().getComm(),
                                       geom.geometry().functionSpace(),
                                       data[0].increment().fieldSet(),
                                       diracPoints[0].increment().fieldSet(),
                                       maxLength,
                                       removeDuplicates);

    // Write to file or to test Log
    const auto & names = data[0].increment().fieldSet().field_names();
    if (profileConf.has("output filepath")) {
      // Write to file
      const auto outputPath = profileConf.getString("output filepath");
      util::write_1d_covariances(geom.geometry().getComm(),
                                 distances,
                                 covariances,
                                 lons,
                                 lats,
                                 levs,
                                 fieldIndexes,
                                 names,
                                 outputPath);
    }

    // Output first 10 values of first 10  profiles to test log
    const int numProfiles = std::min(10, static_cast<int>(distances.size()));
    for (int i=0; i < numProfiles; i++) {
      oops::Log::test() << "Covariance profile for variable " << names[fieldIndexes[i]]
                        << ", at level " << levs[i] << ": " << std::endl;
      const int numValues = std::min(10, static_cast<int>(distances[i].size()));
      const std::vector<double> subDist(distances[i].begin(), distances[i].begin() + numValues);
      const std::vector<double> subCovs(covariances[i].begin(), covariances[i].begin() + numValues);
      oops::Log::test() << "Separation distance: " << subDist << std::endl;
      oops::Log::test() << "Covariance: " << subCovs << std::endl;
  }

  oops::Log::trace() << appname() << "::extract_1d_covariances done" << std::endl;
}

// -----------------------------------------------------------------------------

  void dirac(const eckit::LocalConfiguration & covarConf,
             const eckit::LocalConfiguration & testConf,
             const std::string & id,
             const Geometry_ & geom,
             const oops::JediVariables & vars,
             const State4D_ & xx,
             const Increment4D_ & dxi) const {
    oops::Log::trace() << appname() << "::dirac starting" << std::endl;

    // Get covariance model
    const std::string covarianceModel(covarConf.getString("covariance"));

    // Update ID
    std::string updId = id;
    if (updId != "") {
      updId.append("_");
    }
    updId.append(replaceWhiteSpace(covarianceModel));
    if (covarianceModel == "SABER") {
      const std::string covarianceType = covarConf.getString("covariance type", "parametric");
      updId.append("-" + replaceWhiteSpace(covarianceType));
    }

    // Dirac test
    oops::Log::test() << "Covariance(" << updId << ") dirac test:" << std::endl;

    // Define output increment
    Increment4D_ dxo(dxi, false);

    // Covariance
    std::unique_ptr<Covariance4DBase_> Bmat(Covariance4DFactory_::create(
                                            covarConf, geom, util::templatedVars<MODEL>(vars), xx));

    // Linearize
    Bmat->linearize(xx, geom, covarConf);

    // Multiply
    Bmat->multiply(dxi, dxo);

    // Copy configuration
    eckit::LocalConfiguration outputBConf(testConf.getSubConfiguration("output dirac"));

    // Seek and replace %id% with updId, recursively
    util::seekAndReplace(outputBConf, "%id%", updId);

    // Write output increment
    dxo.write(outputBConf);
    oops::Log::test() << "Covariance(" << updId << ") * Increment:" << dxo << std::endl;

    if (testConf.has("diagnostic points")) {
      oops::Log::test() << "Covariance(" << updId << ") diagnostics:" << std::endl;

      // Print variances
      oops::Log::test() << "- Variances at Dirac points:" << std::endl;
      print_value_at_positions(testConf.getSubConfiguration("dirac"), geom, dxo);

      // Print covariances
      oops::Log::test() << "- Covariances at diagnostic points:" << std::endl;
      print_value_at_positions(testConf.getSubConfiguration("diagnostic points"), geom, dxo);
    }

    if (testConf.has("covariance profile")) {
      oops::Log::test() << "Covariance(" << updId << ") profile:" << std::endl;

      // Get configuration
      eckit::LocalConfiguration covProfileConf(testConf.getSubConfiguration("covariance profile"));

      // Seek and replace %id% with updId, recursively
      util::seekAndReplace(covProfileConf, "%id%", updId);

      // Extract 1D covariance profiles
      extract_1d_covariances(testConf.getSubConfiguration("dirac"),
                             covProfileConf,
                             geom,
                             dxo);
    }

    // Get recursive mode
    const bool runComponentsRecursively = covarConf.getBool("run components recursively", false);

    // Recursive call for hybrid covariance model in recursive model
    if ((covarianceModel == "hybrid") && runComponentsRecursively) {
      // Get components configurations
      std::vector<eckit::LocalConfiguration> confs;
      covarConf.get("components", confs);

      // Initialize component index
      size_t componentIndex = 1;

      // Loop over components
      for (const auto & conf : confs) {
        // Prepare sub-covariance configuration
        const eckit::LocalConfiguration componentConfig(conf, "covariance");

        // Update ID
        const std::string covId(updId + "-cmp" + std::to_string(componentIndex));

        // Call dirac function
        dirac(componentConfig, testConf, covId, geom, vars, xx, dxi);
        ++componentIndex;
      }
    }

    // Ensemble covariance model
    if (covarianceModel == "ensemble" && covarConf.has("localization") &&
      (!covarConf.has("ensemble geometry"))) {
      // Update ID
      std::string locId(updId);
      locId.append("_localization");

      // Dirac test
      oops::Log::test() << "Localization(" << locId<< ") dirac test:" << std::endl;

      // Get localization configuration
      eckit::LocalConfiguration locConfig(covarConf.getSubConfiguration("localization"));

      // Add date to localization configuration
      locConfig.set("date", xx[0].validTime().toString());

      // Define output increment
      Increment4D_ dxo(dxi);

      // Setup localization
      Localization_ Lmat(geom, util::templatedVars<MODEL>(vars), locConfig);

      // Apply localization
      Increment_ dxoSum(dxo[0]);
      for (size_t jsub = 1; jsub < dxo.times().size(); ++jsub) {
        dxoSum.axpy(1.0, dxo[jsub], false);
      }
      Lmat.multiply(dxoSum);
      for (size_t jsub = 0; jsub < dxo.times().size(); ++jsub) {
        dxo[jsub].zero();
        dxo[jsub].axpy(1.0, dxoSum, false);
      }

      // Copy configuration
      eckit::LocalConfiguration outputLConf(testConf.getSubConfiguration("output dirac"));

      // Seek and replace %id% with locId, recursively
      util::seekAndReplace(outputLConf, "%id%", locId);

      // Write output increment
      dxo.write(outputLConf);
      oops::Log::test() << "Localization(" << locId << ") * Increment:" << dxo << std::endl;

      // Print localization diagnostics
      oops::Log::test() << "Localization(" << locId << ") diagnostics:" << std::endl;
      oops::Log::test() << "- Localization at zero separation:" << std::endl;

      // Print value at certain positions
      print_value_at_positions(testConf.getSubConfiguration("dirac"), geom, dxo);
      if (testConf.has("diagnostic points")) {
        oops::Log::test() << "- Localization at diagnostic points:" << std::endl;
        print_value_at_positions(testConf.getSubConfiguration("diagnostic points"), geom, dxo);
      }
    }

    // SABER covariance model without outer blocks
    if ((covarianceModel == "SABER") && (!covarConf.has("saber outer blocks"))) {
      // Get covariance type
      const std::string covarianceType = covarConf.getString("covariance type", "parametric");

      // Recursive call for hybrid covariance type in recursive mode
      if ((covarianceType == "hybrid") && runComponentsRecursively) {
        // Deserialize base parameters
        ErrorCovarianceParametersBase paramsBase;
        paramsBase.deserialize(covarConf);

        // Get components configurations list
        std::vector<eckit::LocalConfiguration> confs;
        covarConf.get("components", confs);

        // Initialize component index
        size_t componentIndex(1);

        for (const auto & conf : confs) {
          // Prepare sub-covariance configuration
          eckit::LocalConfiguration componentConfig(conf, "covariance");
          componentConfig.set("covariance", "SABER");

          // Merge configuration with full configuration (order of arguments matters!)
          componentConfig = util::mergeConfigs(componentConfig, paramsBase.toConfiguration());

          // Update ID
          const std::string covId(updId + "-cmp" + std::to_string(componentIndex));

          // Call dirac function
          dirac(componentConfig, testConf, covId, geom, vars, xx, dxi);
          ++componentIndex;
        }
      }

      // Localization output for ensemble covariance type
      if (covarianceType == "ensemble" && covarConf.has("localization") &&
        (!covarConf.has("ensemble geometry"))) {
        // Update ID
        std::string locId(updId);
        locId.append("_localization");

        // Dirac test
        oops::Log::test() << "Localization(" << locId<< ") dirac test:" << std::endl;

        // Deserialize base parameters
        ErrorCovarianceParametersBase paramsBase;
        paramsBase.deserialize(covarConf);

        // Get localization configuration
        eckit::LocalConfiguration locConfig(covarConf.getSubConfiguration("localization"));

        // Merge configuration with full configuration (order of arguments matters!)
        locConfig = util::mergeConfigs(locConfig, paramsBase.toConfiguration());

        // Get background as FieldSet4D
        oops::FieldSet4D fset4d(xx);

        // Setup localization
        const SaberParametricBlockChain Lmat(geom,
                                             vars,
                                             fset4d,
                                             fset4d,
                                             locConfig);

        // Define output increment
        Increment4D_ dxo(dxi);
        oops::FieldSet4D fset4dDxo(dxo);

        // Apply localization
        Lmat.multiply(fset4dDxo);

        // Reset output (TODO: necessary?)
        for (int jsub = 0; jsub < dxo.times().size(); ++jsub) {
          dxo[jsub].increment().fromFieldSet(fset4dDxo[jsub].fieldSet());
        }

        // Copy configuration
        eckit::LocalConfiguration outputLConf(testConf.getSubConfiguration("output dirac"));

        // Seek and replace %id% with locId, recursively
        util::seekAndReplace(outputLConf, "%id%", locId);

        // Write output increment
        dxo.write(outputLConf);
        oops::Log::test() << "Localization(" << locId << ") * Increment:" << dxo << std::endl;

        // Print localization diagnostics
        oops::Log::test() << "Localization(" << locId << ") diagnostics:" << std::endl;
        oops::Log::test() << "- Localization at zero separation:" << std::endl;

        // Print value at certain positions
        print_value_at_positions(testConf.getSubConfiguration("dirac"), geom, dxo);
        if (testConf.has("diagnostic points")) {
          oops::Log::test() << "- Localization at diagnostic points:" << std::endl;
          print_value_at_positions(testConf.getSubConfiguration("diagnostic points"), geom, dxo);
        }
      }

      // Localization output for ensemble covariance type with several scales
      if (covarianceType == "ensemble" && covarConf.has("scales") &&
          (!covarConf.has("ensemble geometry"))) {
        size_t iscale = 1;
        for (const auto & scaleConfig : covarConf.getSubConfigurations("scales")) {
          // Update ID
          std::string locId(updId);
          locId.append("_localization_wb" + std::to_string(iscale));

          // Dirac test
          oops::Log::test() << "Localization(" << locId<< ") dirac test:" << std::endl;

          // Deserialize base parameters
          ErrorCovarianceParametersBase paramsBase;
          paramsBase.deserialize(covarConf);

          // Get localization configuration
          eckit::LocalConfiguration locConfig(scaleConfig.getSubConfiguration("localization"));

          // Merge configuration with full configuration (order of arguments matters!)
          locConfig = util::mergeConfigs(locConfig, paramsBase.toConfiguration());

          // Get background as FieldSet4D
          oops::FieldSet4D fset4d(xx);

          // Setup localization
          const SaberParametricBlockChain Lmat(geom,
                                               vars,
                                               fset4d,
                                               fset4d,
                                               locConfig);

          // Define output increment
          Increment4D_ dxo(dxi);
          oops::FieldSet4D fset4dDxo(dxo);

          // Apply localization
          Lmat.multiply(fset4dDxo);

          // Reset output (TODO: necessary?)
          for (int jsub = 0; jsub < dxo.times().size(); ++jsub) {
            dxo[jsub].increment().fromFieldSet(fset4dDxo[jsub].fieldSet());
          }

          // Copy configuration
          eckit::LocalConfiguration outputLConf(testConf.getSubConfiguration("output dirac"));

          // Seek and replace %id% with locId, recursively
          util::seekAndReplace(outputLConf, "%id%", locId);

          // Write output increment
          dxo.write(outputLConf);
          oops::Log::test() << "Localization(" << locId << ") * Increment:" << dxo << std::endl;

          // Print localization diagnostics
          oops::Log::test() << "Localization(" << locId << ") diagnostics:" << std::endl;
          oops::Log::test() << "- Localization at zero separation:" << std::endl;

          // Print value at certain positions
          print_value_at_positions(testConf.getSubConfiguration("dirac"), geom, dxo);
          if (testConf.has("diagnostic points")) {
            oops::Log::test() << "- Localization at diagnostic points:" << std::endl;
            print_value_at_positions(testConf.getSubConfiguration("diagnostic points"), geom, dxo);
          }
        }
      }
    }

    oops::Log::trace() << appname() << "::dirac done" << std::endl;
  }

// -----------------------------------------------------------------------------

  void randomization(const ErrorCovarianceToolboxParameters & params,
                     const Geometry_ & geom,
                     const oops::JediVariables & vars,
                     const eckit::LocalConfiguration & covarConf,
                     const State4D_ & xx,
                     const size_t & ntasks,
                     const size_t & nthreads) const {
    oops::Log::info() << "Info     : " << std::endl;
    oops::Log::info() << "Info     : Generate perturbations:" << std::endl;
    oops::Log::info() << "Info     : -----------------------" << std::endl;

    // Build covariance
    oops::Log::info() << "Info     : Build covariance" << std::endl;
    std::unique_ptr<Covariance4DBase_> Bmat(Covariance4DFactory_::create(
                                            covarConf, geom, util::templatedVars<MODEL>(vars), xx));
    Bmat->linearize(xx, geom, covarConf);

    // Create increments
    Increment4D_ dx(geom, util::templatedVars<MODEL>(vars), xx.times());
    Increment4D_ dxsq(geom, util::templatedVars<MODEL>(vars), xx.times());
    Increment4D_ variance(geom, util::templatedVars<MODEL>(vars), xx.times());

    // Initialize variance
    variance.zero();

    // Output options
    const auto & outputPerturbations = params.outputPerturbations.value();
    const auto & outputStates = params.outputStates.value();
    const auto & outputVariance = params.outputVariance.value();

    // Get randomization size
    const size_t & randomizationSize = params.backgroundError.value().randomizationSize.value();
    ASSERT(randomizationSize > 0);

    for (size_t jm = 0; jm < randomizationSize; ++jm) {
      // Generate member
      oops::Log::info() << "Info     : Member " << jm+1 << std::endl;
      Bmat->randomize(dx);

      if (outputPerturbations != boost::none) {
        // Update config
        auto outputPerturbationsUpdated = *outputPerturbations;
        util::setMember(outputPerturbationsUpdated, jm+1);
        setMPI(outputPerturbationsUpdated, ntasks, nthreads);

        // Write perturbation
        oops::Log::test() << "Write perturbation: " << dx;
        dx.write(outputPerturbationsUpdated);
      }

      if (outputStates != boost::none) {
        // Update config
        auto outputStatesUpdated = *outputStates;
        util::setMember(outputStatesUpdated, jm+1);
        setMPI(outputStatesUpdated, ntasks, nthreads);

        // Add background state to perturbation
        State4D_ xp(xx);
        for (int jsub = 0; jsub < dx.times().size(); ++jsub) {
          xp[jsub-dx.first()] += dx[jsub];
        }

        // Write state
        oops::Log::test() << "Write state: " << xp;
        xp.write(outputStatesUpdated);
      }

      // Square perturbation
      dxsq = dx;
      for (int jsub = 0; jsub < dx.times().size(); ++jsub) {
        dxsq[jsub].schur_product_with(dx[jsub]);
      }

      // Update variance
      variance += dxsq;

      oops::Log::info() << "Info     :" << std::endl;
    }

    if (outputVariance != boost::none) {
      if (randomizationSize > 1) {
        // Normalize variance
        double rk_norm = 1.0/static_cast<double>(randomizationSize);
        variance *= rk_norm;
      }

      // Update config
      auto outputVarianceUpdated = *outputVariance;
      setMPI(outputVarianceUpdated, ntasks, nthreads);

      // Write variance
      oops::Log::test() << "Write randomized variance:" << variance[0] << std::endl;
      variance.write(outputVarianceUpdated);
    }
  }

// -----------------------------------------------------------------------------

  std::string replaceWhiteSpace(const std::string & inputStr) const {
    std::string outputStr(inputStr);
    std::replace(outputStr.begin(), outputStr.end(), ' ', '-');
    return outputStr;
  }

// -----------------------------------------------------------------------------
};

}  // namespace saber
